name: Setup environment
description: This action sets up the environment for the project.

inputs:
  python-version:
    description: The version of Python to use.
    required: true
    default: "3.12"
  node-version:
    description: The version of Python to use.
    required: true
    default: "20"

runs:
  using: composite
  steps:
    - name: Setup Poetry
      shell: bash
      run: pipx install poetry

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run setup_env script
      shell: bash
      run: ./scripts/setup_env.sh
