name: Release

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"

env:
  DEFAULT_PYTHON: "3.12"
  DEFAULT_NODE: "20"

permissions:
  contents: write

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/tomtom-apis
    permissions:
      id-token: write
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          node-version: ${{ env.DEFAULT_NODE }}

      - name: Set version
        run: |
          version="${{ github.ref_name }}"
          version=${version#v}
          poetry version ${{ github.ref_name }}

      - name: Build project
        run: poetry build

      - name: Publish project
        run: poetry publish

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*.tar.gz
            dist/*.whl
