name: Update fixtures and test

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      create_pr:
        type: boolean
        description: Create pull request
        default: false
  schedule:
    - cron: "0 0 * * *" # Every day at UTC midnight.

env:
  DEFAULT_PYTHON: "3.12"
  DEFAULT_NODE: "20"

permissions:
  contents: write
  pull-requests: write

jobs:
  update_fixtures:
    runs-on: ubuntu-latest
    name: Update fixtures
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.PR2D2_APP_ID }}
          private-key: ${{ secrets.PR2D2_APP_PRIVATE_KEY }}

      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          node-version: ${{ env.DEFAULT_NODE }}

      - name: Update fixtures script
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
        run: poetry run python scripts/update_test_fixtures.py

      - name: Create pull request
        if: github.event.inputs.create_pr == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update fixtures
          committer: pr-2d2[bot] <184697184+pr-2d2[bot]@users.noreply.github.com>
          author: pr-2d2[bot] <184697184+pr-2d2[bot]@users.noreply.github.com>
          branch: ci/update_fixtures
          delete-branch: true
          title: Update fixtures
          body: |
            New fixture files for tests.
            Full log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: |
            automated pr

      - name: Run tests
        run: poetry run pytest

      - name: Upload fixtures for failed test
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fixtures
          path: tests/fixtures
          retention-days: 14
