name: Update fixtures

on: # yamllint disable-line rule:truthy
  workflow_dispatch: ~
  schedule:
    - cron: "0 0 * * *" # every day at midnight

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  update_fixtures:
    runs-on: ubuntu-latest
    name: Update fixtures
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: poetry

      - name: Setup env
        run: |
          ./scripts/setup_env.sh

      - name: Update fixtures script
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
        run: python scripts/update_test_fixtures.py

      - name: Run tests
        run: poetry run pytest

      - name: Upload fixtures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fixtures
          path: tests/fixtures
          retention-days: 14
